### ISSUE TITLE
Work with Joomla Template

### ISSUE THREAD

**Issue by allensph** [Syndes/Joomla-MRBS-Bridge#1]
Besides using Iframe Module (iframe isn't a good way for RWD)
is there any way to show MRBS with Joomla Templates ? (That means show MRBS in content with Joomla Menu / Module positions.)

**Comment by ocean123** [comment]
The only way to show MRBS with in Joomla is to build a extension to integrate MRBS in Joomla. Maybe a combination of a joomla plugin and module or something.

(be free to build one)

**Comment by ocean123** [comment]
Joomla authentication has now been included in the default branch of MRBS. It will appear in the next release (ie the one after 1.5.0).
