### ISSUE TITLE
3.6 breaks bridge

### ISSUE THREAD

**Issue by GitHubAndDance** [Syndes/Joomla-MRBS-Bridge#2]
Fatal error: Cannot redeclare utf8_substr() (previously declared in /**_/public_html/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:92) in /home/**_/public_html/booking/language.inc on line 1338

**Comment by ocean123** [comment]
Hi, Can you give some more information? Is there some error you can give my to look for?

**Comment by rapasae** [comment]
Hi, congratulations for your project.
Same problem for me.

>  **mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare utf8_substr() (previously declared in /plesk/vhosts/httpdocs/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:92) in /plesk/vhosts/httpdocs/mrbs/language.inc on line 1090**

**Comment by GitHubAndDance** [comment]
Sorry, did not see your reply - what kind of info do you need? All I see is
the error code: _PHP Fatal error: Cannot redeclare utf8_substr()
(previously declared in...._

On Thu, Jul 14, 2016 at 10:25 PM, ocean123 notifications@github.com wrote:

> Hi, Can you give some more information? Is there some error you can give
> my to look for?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Syndes/Joomla-MRBS-Bridge/issues/2#issuecomment-232781619,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFqz7TXwTkqseKbXgMDyEF9QAS_YpEdHks5qVpshgaJpZM4JLV4T
> .

## 

mvh.

Kristian Østerbæk

**Comment by ocean123** [comment]
Okey, well thats a mrbs issue. that is not a mobs-bridge file.
So you have to go to http://mrbs.sourceforge.net and search there for a solution.
best regards

**Comment by ocean123** [comment]
Joomla authentication has now been included in the default branch of MRBS. It will appear in the next release (ie the one after 1.5.0).
