### ISSUE TITLE
Joomla-MRBS-Bridge doesn't work in Joomla 3.61

### ISSUE THREAD

**Issue by mascetti** [Syndes/Joomla-MRBS-Bridge#3]
hello, I used Your bridge for over one year in my college to reserve laboratories. Unlucky i've noticed that after Joomla's update at V3.61 the bridge stopped to work. If i load the MRBS homepage, I receive a blank page. I tried to reinstall MRBS, it works stand-alone, but if i install the bridge it stops to work.
I transferred MRBS installation and database in a Joomla 3.51 environment and it works. So I think the problem is only in version 3.61.
Can u solve this Issue ?
Thanks in advance and best regards
lello

UPDATE:
I think the problem can be in joomla.php file: if i comment the line //require ( 'joomla.php' ); in config.inc.php MRBS works well. If the line works, i receive a blank page. Added screenshots.

Lello.

![2016-08-15_195034](https://cloud.githubusercontent.com/assets/21014097/17673564/f568c81c-6321-11e6-8955-931efdde719e.jpg)

![2016-08-15_195245](https://cloud.githubusercontent.com/assets/21014097/17673733/cc575e56-6322-11e6-81aa-9a0a6408ef36.jpg)

**Comment by ocean123** [comment]
Sorry I can't help you at the moment. To many projects. And I have tried to find the issue with no result. So when someone has find the issue please post it here and I will update the files.

**Comment by ruben40** [comment]
I have the same problem with version 3.6.2. After the upgrade I found the plugin joomla User - Profile disabled, I reactivated it but not work the same. I'm thinking of doing the downgrade but it is complicated.

**Comment by rapasae** [comment]
I found a workaround.
Error log shows:

> mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare utf8_substr() (previously declared in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:92) in mrbs/language.inc on line 1090
> 
>  Cannot redeclare utf8_strlen() (previously declared in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:23) in mrbs/language.inc on line 1334

and:

> mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required 'auth/auth_jm_gid.inc' (include_path='.:') in mrbs/mrbs_auth.inc on line 5

Its related with other issue or perhaps its the same [https://github.com/Syndes/Joomla-MRBS-Bridge/issues/2].

Comment functions _**utf8_strlen**_ and _**utf8_substr**_ in **mrbs/languaje.inc**.
Rename or copy **mrbs/auth/auth_jm.inc** to **mrbs/auth/auth_jm_gid.inc**.

**Comment by mascetti** [comment]
It doesn't work for me... I did what you said, MRBS works, but i must log in manually. It means the bridge doesn't work.
Please can You share here your working langage.inc ?
Thx

**Comment by ocean123** [comment]
I is not in that part. Joomla changed some code and now it is not possible to get the write information from Joomla that is needed for MRBS.
You have to find the write code to get information from Joomla. Somewhere in joomla.php you have to change the php-code. I think its somewhere between line 20 and 100

**Comment by rapasae** [comment]
Working for me with Joomla 3.6.2, MRBS 1.4.10
Attached, you can get my language.inc

[language.inc.txt](https://github.com/Syndes/Joomla-MRBS-Bridge/files/451889/language.inc.txt)

If you get same errors in your log file, it should work.

**Comment by ocean123** [comment]
You are using an old version of language.inc !
pay attention for the database update.
please backup your stuff before trying

**Comment by mascetti** [comment]
This file doesn't work for me... MRBS 1.5.0 stops and gives a blank page. Restored old file and it's ok, but not working bridge.
Waiting for something new...

**Comment by ruben40** [comment]
Someone the previous joomla bridge software for the 1.4.10 version of MRBS? I would like to test.

**Comment by Theophilix** [comment]
Hello,

I got help from a very good javascript/php programmer. He removed old deprecated code from language.inc (Changing MRBS root is not a good solution, I know... but I'm trying to talk to the MRBS guys about this: https://sourceforge.net/p/mrbs/patches/58/) and removed some error handling problems in joomla.php.
Please try the files attached. Personally, I don't have enough programming skills to check if the changes / deletions are absolutely necessary...

[language.inc.txt](https://github.com/Syndes/Joomla-MRBS-Bridge/files/465796/language.inc.txt)
[joomla.php.txt](https://github.com/Syndes/Joomla-MRBS-Bridge/files/465797/joomla.php.txt)

Greetings,
Theophilix

**Comment by ocean123** [comment]
Language.inc.txt is NOT a file which I support. That is a part of MRBS Software.
Always backup the old one.

**Comment by mascetti** [comment]
It doesen't work for me. Using the Theophilix's language.inc i get a blank page. Using only joomla.php file MRBS works, but no bridge function.

**Comment by ocean123** [comment]
You have to search in the part that the bridge is getting information from Joomla.
Joomla has change the way a third party software is getting information.
Somewhere between line 20 and 100 in joomla.php

**Comment by Theophilix** [comment]
The programmer of MRBS says:

> I don't think MRBS uses any deprecated features. If you run MRBS on PHP 7 with an error reporting level of -1, then none are reported. Which language features do you think are causing a problem? I think the issue is that the Joomla MRBS Bridge is a separate project and not part of MRBS and I suspect it is still using an old version of language.inc.

Source: https://sourceforge.net/p/mrbs/patches/58/

**Comment by ocean123** [comment]
That is correct. The issue is in the bridge file "joomla.php" thats what I already said. But I am not able to fix the issue because of the time. And in my bridge software there is NO language.inc.

**Comment by mascetti** [comment]
I hope u can fix it in the near future..

**Comment by jberanek** [comment]
Well, it's not that MRBS is using PHP functions deprecated in PHP 7, it's that it has implemented some functions that Joomla has also implemented, like utf8_strlen:

http://fossies.org/dox/Joomla_3.6.2-Stable-Full_Package/vendor_2joomla_2string_2src_2phputf8_2mbstring_2core_8php.html

**Comment by Theophilix** [comment]
I copied Campbell Morrisons new files from https://sourceforge.net/p/mrbs/hg-code/ci/default/tree/web/. And overwrote with joomla mrbs-files.  It works with login, but the layout is wrong. Here the screenshots from my test site: test.eventtableedit.com:

![screenshot mrbs error with login](https://cloud.githubusercontent.com/assets/17642779/18680717/316c429e-7f65-11e6-9857-6821bdf316eb.png)

**Comment by ocean123** [comment]
The first error has to something with Enable the “User Profile” plugin in Joomla
The second screen I also have and still can't help because of the time.
I am sorry.

**Comment by Theophilix** [comment]
Here comes the solution as a workaround (until Ocean has more time to fix this):
1. Download default mrbs tree from https://sourceforge.net/p/mrbs/hg-code/ci/default/tree/web/
2. Copy it to your empty mrbs folder.
3. Download Joomla-MRBS-Bridge.
4. Copy the files to MRBS folder and overwrite files. 
5. Go to mrbs/lang/ and the line $vocab["norights"] in your own language file like described on Joomla-MRBS-Bridge start / home site (scroll down).
6. In joomla.php: uncomment line 160-162 (so some errors are ignored)

**Comment by ocean123** [comment]
Only uncomment line 160-162 will be enough

**Comment by ocean123** [comment]
jimport joomla.user.helper is already on line 34

**Comment by ocean123** [comment]
thanks Theophilix for you help.
I will update the files soon

**Comment by Theophilix** [comment]
Thanks, I changed the workaround info.

**Comment by mascetti** [comment]
I'm sorry, but i haven't understood the step n.5. Please can you explain better ?

**Comment by ocean123** [comment]
mascetti  Don't follow the steps above.
just download the bridge files and follow the installation manual.
the files are up to date now.

**Comment by mascetti** [comment]
thx

**Comment by jberanek** [comment]
A better way than editing your lang file would be to add to config.inc.php like below (if you're using English):

`$vocab_override['en']["norights"] = ...
`

**Comment by mascetti** [comment]
I did all, but I still get a white page.. If I comment "require ( 'joomla.php' );" in config.inc.php MRBS works perfectly.

**Comment by Theophilix** [comment]
@ocean123: Please also add german vocab override.
`
$vocab_override['de']["norights"] = "
    Sie haben keine Berechtigung, diesen Eintrag zu ändern.
    <p class='login_reg'>
    <a class='login' href='../index.php?option=com_users&amp;view=login' TARGET='_parent' id='btnLogin'>Login</a> or
    <a class='registration' href='../index.php?option=com_users&amp;view=registration' TARGET='_parent' >Register</a>
    </p>
    ";`

**Comment by ocean123** [comment]
Joomla authentication has now been included in the default branch of MRBS. It will appear in the next release (ie the one after 1.5.0).

**Comment by debreton** [comment]
I the next release (ie the one after 1.5.0) available somewhere?

**Comment by ocean123** [comment]
Joomla authentication has now been included in the default branch of MRBS. It will appear in the next release (ie the one after 1.5.0).

There is no support any more please see MRBS new release.

**Comment by jberanek** [comment]
You can download the latest MRBS from https://sourceforge.net/p/mrbs/hg-code/ci/default/tarball - this will be packaged as a release "at some point".
