### ISSUE TITLE
User info box missing

### ISSUE THREAD

**Issue by Theophilix** [Syndes/Joomla-MRBS-Bridge#4]
I use the newest MRBS version from default branch and the newest Joomla-MRBS-Bridge version.
But: the user info box in the upper right corner, present in "pure" MRBS (see attachment), 
![user info box](https://cloud.githubusercontent.com/assets/17642779/18726682/dd401a92-8045-11e6-94ad-34128866d9fe.png)

is gone when I install Joomla-MRBS-Bridge:

![user info box missing](https://cloud.githubusercontent.com/assets/17642779/18727169/c9168a86-8047-11e6-9a34-9f87b9ebbe84.png)

**Comment by ocean123** [comment]
Joomla authentication has now been included in the default branch of MRBS. It will appear in the next release (ie the one after 1.5.0).

**Comment by Theophilix** [comment]
Great, thank you very much for your effort!
